### ISSUE TITLE
demo for groups and or multi user authorization

### ISSUE THREAD

**Issue by drlukeangel** [cfjedimaster/StrongLoopDemos#2]
Hello,
  Is there a demo for groups/roles and/or multi user authorization for crud properties. This can be done by using roles/groups., or storing a collection of userid's.   In your blog example it would mean anyone with the role editor would be able to edit the post or the post could contain a array of userid's that are allowed to edit it.  Curious to see what the best approach is on that. 
thanks

**Comment by cfjedimaster** [comment]
Sorry no, I don't have a demo of that.

**Comment by drlukeangel** [comment]
cool thanks I saw you work at ibm and this was on the strongloop email that went out so I thought you were in the group. I liked your blog post about the authorization component which lead me to this repo. My suggestion with extending the user model bug would be replace DogThrowUpOn to be DogWalker to show the correlation of have two foreign key user models that could be both owners. Have a great day.
