### ISSUE TITLE
Thanks for tutorial! Is there any new ideas? 

### ISSUE THREAD

**Issue by ApayRus** [cfjedimaster/StrongLoopDemos#3]
Hi, thanks for your [tutorial](https://strongloop.com/strongblog/working-with-file-storage-and-loopback/) 
Can I ask you 3 questions? 

1) I had the same idea with promises... But then I thought, why not use multer and send form with all data - strings and files in one request? I didn't realize it yet and still researching. (why I still appreciate loopback-storage over than multer, is acl. I hope, that acl is more easy to set in lb-storage). 

2) In your current example I didn't understand, why first we send json and create model on server, then after all "sendFile" promises, we update the model instance? It is not better to get first all promises, then put all data to json and create model at the end?

3) I only started to use loopback, and I like it too. But is it still actual (until June 2018 ? ). Or may be appeared better things?

**Comment by cfjedimaster** [comment]
1) To enable that, you would need a custom end point to accept and handle the data. Doable for sure.

2) We don't create the model on the server. The model defines the Cat API is already created. Instead we send data for a new cat. A subtle distinction but important. As for why I make the cat first and then upload versus all 3 at once - no real reason - that's anouther way of doing it.

3) LoopBack is still in development - please see the blog. They are working on v4 now. (I no longer work for IBM.)

**Comment by ApayRus** [comment]
Thanks for answer
